<h1>Импорт библиотек

In [21]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [22]:
def sum_prod(X, V):
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''
    if len(X) != len(V):
        raise ValueError("Количество матриц и векторов должно быть одинаковым.")
    
    result = 0
    for matrix, vector in zip(X, V):
        result += np.dot(matrix, vector)
    
    return result

In [23]:

def run_test(test_number, x, v, expected_result):
    func_result = sum_prod(x, v)
    assert np.array_equal(func_result, expected_result), (
        f"Test №{test_number} Failed. Your result: \n{func_result}"
    )
    print(f"Test №{test_number} Successful. \nOutput: \n{func_result}")

def test():
    test_cases = [
        {
            "test_number": 1,
            "x": [np.array([[0, 1], [2, 3]])],
            "v": [np.array([[1], [1]])],
            "expected_result": np.array([[1], [5]])
        },
        {
            "test_number": 2,
            "x": [np.array([[10, 20], [30, 40]]), np.array([[50, 60], [70, 80]])],
            "v": [np.array([[0], [0]]), np.array([[0], [0]])],
            "expected_result": np.array([[0], [0]])
        },
        {
            "test_number": 3,
            "x": [np.array([[10, 20], [30, 40]]), np.array([[50, 60], [70, 80]])],
            "v": [np.array([[1], [1]]), np.array([[1], [1]])],
            "expected_result": np.array([[140], [220]])
        }
    ]

    for case in test_cases:
        run_test(case["test_number"], case["x"], case["v"], case["expected_result"])

test()

Test №1 Successful. 
Output: 
[[1]
 [5]]
Test №2 Successful. 
Output: 
[[0]
 [0]]
Test №3 Successful. 
Output: 
[[140]
 [220]]


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [24]:
def binarize(M, threshold=0.5):
    # Your code goes here
    pass

<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [25]:
def unique_rows(mat):
    # Your code goes here
    pass

def unique_columns(mat):
    # Your code goes here
    pass

<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [26]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [27]:
def chess(m, n, a, b):
    # Your code goes here
    pass

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [28]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [29]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [30]:
# Your code goes here